export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_PRODUCT_BY_CATEGORY_REQUEST =
  "GET_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAIL = "GET_PRODUCT_BY_CATEGORY_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAIL = "ADD_PRODUCT_REVIEW_FAIL";
export const ADD_PRODUCT_REVIEW_RESET = "ADD_PRODUCT_REVIEW_RESET";

export const LIST_PRODUCT_REVIEW_REQUEST = "LIST_PRODUCT_REVIEW_REQUEST";
export const LIST_PRODUCT_REVIEW_SUCCESS = "LIST_PRODUCT_REVIEW_SUCCESS";
export const LIST_PRODUCT_REVIEW_FAIL = "LIST_PRODUCT_REVIEW_FAIL";
export const LIST_PRODUCT_REVIEW_RESET = "LIST_PRODUCT_REVIEW_RESET";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_RESET = "EDIT_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";
export const GET_SINGLE_PRODUCT_RESET = "GET_SINGLE_PRODUCT_RESET";
